version: '3.1'
services:
  postgres:
    container_name: postgres-service
    image: postgres:15.3
    env_file:
      - .env
    ports:
      - 5432:5432

  rabbitmq:
    container_name: rabbitmq-service
    image: rabbitmq:3-management
    ports:
      # rabbitmq
      - 5672:5672
      # admin
      - 15672:15672
    env_file:
      - .env
    depends_on:
      - postgres
  
  celery:
    container_name: celery-worker
    build:
      context: .
      dockerfile: ./docker/celery/Dockerfile
    env_file:
      - .env
    depends_on:
      - rabbitmq
  
  celery_2:
    container_name: celery-worker-2
    build:
      context: .
      dockerfile: ./docker/celery/Dockerfile
    env_file:
      - .env
    depends_on:
      - rabbitmq

  flower:
    container_name: celery-flower
    build:
      context: .
      dockerfile: ./docker/celery-flower/Dockerfile
    env_file:
      - .env
    ports:
      - 5001:5001
    depends_on:
      - rabbitmq

  fastapi:
    container_name: fastapi-app
    build:
      context: .
      dockerfile: ./docker/fastapi/Dockerfile
    ports:
      # uvicorn server
      - 8000:8000
    depends_on:
      - rabbitmq
      - celery
    env_file:
      - .env
  


